print("hello its me mehmet hasan")
print("my routine will be different from others")
print("so i first wake up at7am when its time for school")
print("i brush my teeth and wash my face")
print("then if i had alot of time then i can warch tv while eating breakfast")
print("but if dont then i just eat breakfast and go to school at 7:20am")
print("when the school ended i go home and watch tv again")
print("then i eat lunch,read with hujur and then i go to sleep at 5:00pm on sunday,tuesday and thursday")
print("then i wake up at 6:40pm and \nwatch tv again and then i do homework with my mom at 7:00pm")
print("\t then after i finished all of my homework i watch tv again then i eat dinner at 10pm and go to sleep")