name = input("What is your name:")
birth_place = input("Where were you born:")
video_games = input("what is your favourate video game:")
board_game = input("What is your favourate board game:")
tabletop_game = input("what is your favourate tabletop game:")
sports = input("What is your favourate sports:")
night_party_games = input("What is your favourate night party game:")
date_of_birth = input("When were you born:")
mobile_games = input("What is your favourate mobile game:")
AI = input("What is your favourate AI:")
card_game = input("What is your favourate card game:")

print("Your name is", name ,"you were born inside", birth_place ,"your favourate video game is", video_games , "your favourate board game is", board_game ,"your favourate tabletop game is", tabletop_game ,"your favourate sports is", sports , "your favourate night party game is", night_party_games , "your were born in", date_of_birth , "your favourate mobile game is", mobile_games , "your favourate artificial inteligence", AI , "your favourate car game is", card_game)
print("well met my name is chatbox a special helper friend agent ask me anything i know anything")